CREATE TABLE IF NOT EXISTS model(
	name TEXT UNIQUE NOT NULL,
	path_str TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS terrain(
	model TEXT NOT NULL,
	x REAL NOT NULL,
	y REAL NOT NULL,
	z REAL NOT NULL, 
	CONSTRAINT fk_model FOREIGN KEY (model) REFERENCES model(name)
);
